---
kind: pipeline
type: docker
name: default

steps:
  - name: Test + build
    image: python:3.9
    commands:
      - pip install flake8 pytest
      - pip install -r requirements_dev.txt
      - pytest
      - make fmt
