---
kind: pipeline
type: docker
name: default

steps:
  - name: Test
    image: python:3.9
    commands:
      - pip install -r requirements_dev.txt
      - pytest
  - name: Format
    image: python:3.9
    commands:
      - make fmt
